"""
Email composition module.

This module is responsible for composing emails with video summaries.
"""

import os
from datetime import datetime
from tiktok_analyzer.utils.logger import setup_logger

logger = setup_logger()

class EmailComposer:
    """
    Composes emails with video summaries.
    """
    
    def __init__(self):
        """Initialize the email composer."""
        pass
    
    def compose_email(self, summaries, influencers):
        """
        Compose an email with summaries for each influencer's video.
        
        Args:
            summaries: Dictionary mapping usernames to video summaries
            influencers: List of influencer data dictionaries
            
        Returns:
            Email content as HTML
        """
        try:
            logger.info(f"Composing email with {len(summaries)} summaries")
            
            influencer_map = {influencer['username']: influencer for influencer in influencers}
            
            email_content = self._generate_email_content(summaries, influencer_map)
            
            logger.info(f"Email composed successfully: {len(email_content)} characters")
            return email_content
            
        except Exception as e:
            logger.error(f"Error composing email: {str(e)}")
            return self._generate_error_email(str(e))
    
    def _generate_email_content(self, summaries, influencer_map):
        """
        Generate the email content with summaries.
        
        Args:
            summaries: Dictionary mapping usernames to video summaries
            influencer_map: Dictionary mapping usernames to influencer data
            
        Returns:
            Email content as HTML
        """
        current_date = datetime.now().strftime("%Y-%m-%d")
        
        email_content = f"""
        <html>
        <head>
            <style>
                body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
                .container {{ max-width: 800px; margin: 0 auto; padding: 20px; }}
                .header {{ background-color: #f8f9fa; padding: 20px; text-align: center; }}
                .summary {{ margin-bottom: 30px; border-bottom: 1px solid #eee; padding-bottom: 20px; }}
                .influencer-info {{ display: flex; align-items: center; margin-bottom: 15px; }}
                .influencer-avatar {{ width: 50px; height: 50px; border-radius: 50%; margin-right: 15px; }}
                .influencer-name {{ font-size: 18px; font-weight: bold; }}
                .influencer-stats {{ font-size: 14px; color: #666; }}
                .summary-content {{ margin-top: 15px; }}
                .footer {{ text-align: center; margin-top: 30px; font-size: 12px; color: #999; }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>TikTok Influencer Video Summaries</h1>
                    <p>Top 10 TikTok Influencers - Latest Video Summaries for {current_date}</p>
                </div>
        """
        
        for username, summary in summaries.items():
            influencer = influencer_map.get(username, {})
            display_name = influencer.get('display_name', username)
            follower_count = influencer.get('follower_count', 'N/A')
            avatar_url = influencer.get('avatar_url', '')
            
            email_content += f"""
                <div class="summary">
                    <div class="influencer-info">
                        <img class="influencer-avatar" src="{avatar_url}" alt="{display_name}" onerror="this.src='https://via.placeholder.com/50'">
                        <div>
                            <div class="influencer-name">@{username}</div>
                            <div class="influencer-stats">Followers: {follower_count:,}</div>
                        </div>
                    </div>
                    <div class="summary-content">
                        <h3>Latest Video Summary:</h3>
                        <p>{summary}</p>
                    </div>
                </div>
            """
        
        email_content += f"""
                <div class="footer">
                    <p>This email was automatically generated by the TikTok Influencer Analysis Application.</p>
                    <p>Generated on {current_date}</p>
                </div>
            </div>
        </body>
        </html>
        """
        
        return email_content
    
    def _generate_error_email(self, error_message):
        """
        Generate an error email when something goes wrong.
        
        Args:
            error_message: Error message to include in the email
            
        Returns:
            Error email content as HTML
        """
        current_date = datetime.now().strftime("%Y-%m-%d")
        
        email_content = f"""
        <html>
        <head>
            <style>
                body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
                .container {{ max-width: 800px; margin: 0 auto; padding: 20px; }}
                .header {{ background-color: #f8f9fa; padding: 20px; text-align: center; }}
                .error {{ color: #dc3545; margin: 20px 0; padding: 15px; border: 1px solid #dc3545; }}
                .footer {{ text-align: center; margin-top: 30px; font-size: 12px; color: #999; }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>TikTok Influencer Video Summaries - Error Report</h1>
                    <p>Error occurred on {current_date}</p>
                </div>
                
                <div class="error">
                    <h2>An error occurred while processing TikTok influencer videos:</h2>
                    <p>{error_message}</p>
                </div>
                
                <p>Please check the application logs for more details.</p>
                
                <div class="footer">
                    <p>This email was automatically generated by the TikTok Influencer Analysis Application.</p>
                    <p>Generated on {current_date}</p>
                </div>
            </div>
        </body>
        </html>
        """
        
        return email_content
